import { Bot, Code2, Lightbulb, PenLine, Sparkles } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import AgentPanel from "../components/chat/AgentPanel";
import InputBar from "../components/chat/InputBar";
import MessageList from "../components/chat/MessageList";
import { useChat } from "../hooks/useChat";
import { api } from "../lib/api";
import { useSettingsStore } from "../lib/settingsStore";
import type { ChatMode } from "../types";

const SUGGESTIONS = [
  {
    icon: Code2,
    title: "Explain code",
    prompt: "Explain what this Python function does and how to improve it.",
  },
  {
    icon: PenLine,
    title: "Draft an email",
    prompt: "Draft a polite follow-up email to a client about a delayed deliverable.",
  },
  {
    icon: Lightbulb,
    title: "Brainstorm",
    prompt: "Give me five creative product names for an AI note-taking app.",
  },
  {
    icon: Sparkles,
    title: "Summarise",
    prompt: "Summarise the key ideas of LangChain LCEL in three bullet points.",
  },
];

const DB_EXAMPLES = [
  "How many users are registered?",
  "Show the latest 10 chat threads.",
  "How many messages were created today?",
  "List top 5 users by number of threads.",
  "Show notes created in the last 7 days.",
  "What are the most recently updated notes?",
];

export default function ChatPage() {
  const { messages, busy, error, send, activeId } = useChat();
  const availableModels = useSettingsStore((s) => s.availableModels);
  const [input, setInput] = useState("");
  const [files, setFiles] = useState<File[]>([]);
  const [mode, setMode] = useState<ChatMode>("chat");
  const [imageGenerateEnabled, setImageGenerateEnabled] = useState(false);
  const [attachmentError, setAttachmentError] = useState<string | null>(null);
  const [ragEnabled, setRagEnabled] = useState(true);
  const [agentOpen, setAgentOpen] = useState(false);
  const scrollRef = useRef<HTMLDivElement | null>(null);

  const imageModelId =
    availableModels.find((m) => m.id.toLowerCase().includes("imagen"))?.id ||
    "gemini/imagen-4.0-fast-generate-001";

  // Context-aware follow-up suggestions, generated by the backend LLM from the
  // recent message history. Refreshed each time the assistant sends a new
  // message (i.e. the message count grows and we're not currently busy).
  const [followUps, setFollowUps] = useState<string[]>([]);
  const lastFetchedSignatureRef = useRef<string>("");

  useEffect(() => {
    if (busy || !activeId) return;
    const lastAssistant = [...messages].reverse().find((m) => m.role === "assistant");
    if (!lastAssistant) {
      setFollowUps([]);
      return;
    }
    // Avoid re-fetching for the same conversation state.
    const signature = `${activeId}:${messages.length}:${lastAssistant.id ?? ""}`;
    if (signature === lastFetchedSignatureRef.current) return;
    lastFetchedSignatureRef.current = signature;

    let cancelled = false;
    api
      .getSuggestions(activeId)
      .then((items) => {
        if (cancelled) return;
        setFollowUps(Array.isArray(items) ? items.slice(0, 4) : []);
      })
      .catch(() => {
        if (!cancelled) setFollowUps([]);
      });
    return () => {
      cancelled = true;
    };
  }, [activeId, busy, messages]);

  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
  }, [messages, busy]);

  const onSend = async () => {
    const text = input;
    if (!text.trim() && files.length === 0) return;
    setAttachmentError(null);
    setInput("");
    const selectedFiles = files;
    setFiles([]);
    const modelOverride = imageGenerateEnabled ? imageModelId : undefined;
    await send(
      text || "Analyze the attached files and answer.",
      selectedFiles,
      mode,
      modelOverride,
      ragEnabled
    );
    if (imageGenerateEnabled) {
      setImageGenerateEnabled(false);
    }
  };

  const empty = messages.length === 0;

  const onPickFollowUp = async (prompt: string) => {
    if (busy) return;
    await send(prompt, [], "chat", undefined, ragEnabled);
  };

  const onRunDbExample = async (prompt: string) => {
    if (busy) return;
    setInput("");
    await send(prompt, [], "sql", undefined, ragEnabled);
  };

  return (
    <div className="flex h-full flex-col">
      <div ref={scrollRef} className="flex-1 overflow-y-auto">
        {empty ? (
          <Hero onPick={(p) => setInput(p)} />
        ) : (
          <>
            <MessageList messages={messages} busy={busy} />
            {!busy && followUps.length > 0 && (
              <div className="mx-auto mb-2 w-full max-w-5xl px-3 sm:px-4">
                <div className="mb-2 text-xs font-medium uppercase tracking-wider text-slate-400">
                  Suggested follow-ups
                </div>
                <div className="flex flex-wrap gap-2">
                  {followUps.map((s) => (
                    <button
                      key={s}
                      onClick={() => void onPickFollowUp(s)}
                      className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-sm text-slate-200 transition hover:border-accent-500/40 hover:bg-white/10"
                    >
                      {s}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
        {(error || attachmentError) && (
          <div className="mx-auto mb-4 max-w-3xl px-4">
            <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-300">
              {attachmentError || error}
            </div>
          </div>
        )}
      </div>
      <div className="mx-auto mb-2 flex w-full max-w-5xl items-center justify-between gap-2 px-3 sm:px-4">
        <div className="text-xs text-slate-500">
          {mode === "sql"
            ? "Database mode: query your DB in plain English"
            : "Chat mode — live data auto-detected for news, sports, crypto & weather"}
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setAgentOpen(true)}
            className="flex items-center gap-1.5 rounded-full border border-accent-400/40 bg-accent-500/10 px-3 py-1 text-xs font-semibold text-accent-200 transition hover:bg-accent-500/20"
            title="Open live agent (auto-selects tools)"
          >
            <Bot className="h-3.5 w-3.5" />
            Live Agent
          </button>
          <button
            type="button"
            onClick={() => setMode((m) => (m === "sql" ? "chat" : "sql"))}
            className={
              "rounded-full border px-3 py-1 text-xs font-semibold transition " +
              (mode === "sql"
                ? "border-emerald-400/40 bg-emerald-500/10 text-emerald-300"
                : "border-white/10 bg-white/5 text-slate-300 hover:bg-white/10")
            }
            title="Toggle database mode"
          >
            {mode === "sql" ? "DB Mode: ON" : "DB Mode: OFF"}
          </button>
          <button
            type="button"
            onClick={() => setRagEnabled((v) => !v)}
            className={
              "rounded-full border px-3 py-1 text-xs font-semibold transition " +
              (ragEnabled
                ? "border-cyan-400/40 bg-cyan-500/10 text-cyan-200"
                : "border-white/10 bg-white/5 text-slate-300 hover:bg-white/10")
            }
            title="Toggle PDF/document retrieval (RAG)"
          >
            {ragEnabled ? "RAG: ON" : "RAG: OFF"}
          </button>
        </div>
      </div>
      <AgentPanel open={agentOpen} onClose={() => setAgentOpen(false)} />
      {mode === "sql" && (
        <div className="mx-auto mb-2 w-full max-w-5xl px-3 sm:px-4">
          <div className="mb-2 text-xs font-medium uppercase tracking-wider text-emerald-300">
            Try Database Questions
          </div>
          <div className="flex flex-wrap gap-2">
            {DB_EXAMPLES.map((prompt) => (
              <button
                key={prompt}
                onClick={() => void onRunDbExample(prompt)}
                className="rounded-full border border-emerald-400/30 bg-emerald-500/10 px-3 py-1.5 text-sm text-emerald-200 transition hover:border-emerald-300/50 hover:bg-emerald-500/20"
              >
                {prompt}
              </button>
            ))}
          </div>
        </div>
      )}
      <InputBar
        value={input}
        files={files}
        busy={busy}
        onChange={setInput}
        onFilesChange={setFiles}
        imageGenerateEnabled={imageGenerateEnabled}
        onToggleImageGenerate={() => setImageGenerateEnabled((v) => !v)}
        onValidationError={setAttachmentError}
        onSend={onSend}
      />
    </div>
  );
}

function Hero({ onPick }: { onPick: (s: string) => void }) {
  return (
    <div className="mx-auto flex h-full max-w-3xl flex-col items-center justify-center px-6 py-16 text-center">
      <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-accent-500 to-fuchsia-500 shadow-2xl shadow-accent-500/40">
        <Sparkles className="h-7 w-7 text-white" strokeWidth={2.4} />
      </div>
      <h1 className="bg-gradient-to-br from-white via-slate-200 to-slate-400 bg-clip-text text-3xl font-semibold tracking-tight text-transparent sm:text-4xl">
        How can I help you today?
      </h1>
      <p className="mt-3 max-w-md text-sm text-slate-400">
        Ask anything — code, ideas, summaries, drafts. Powered by the LiteLLM gateway.
      </p>
      <div className="mt-10 grid w-full grid-cols-1 gap-3 sm:grid-cols-2">
        {SUGGESTIONS.map((s) => (
          <button
            key={s.title}
            onClick={() => onPick(s.prompt)}
            className="group flex items-start gap-3 rounded-xl border border-white/10 bg-white/5 p-4 text-left transition hover:-translate-y-0.5 hover:border-accent-500/40 hover:bg-white/10"
          >
            <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-white/10 text-accent-400 transition group-hover:bg-accent-500/20">
              <s.icon className="h-4 w-4" />
            </div>
            <div className="min-w-0">
              <div className="text-sm font-medium text-slate-100">{s.title}</div>
              <div className="truncate text-xs text-slate-400">{s.prompt}</div>
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}
